#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=0 --output_dir="../experiments/exp_ecc_pubmed_0" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=1 --output_dir="../experiments/exp_ecc_pubmed_1" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=2 --output_dir="../experiments/exp_ecc_pubmed_2" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=3 --output_dir="../experiments/exp_ecc_pubmed_3" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=4 --output_dir="../experiments/exp_ecc_pubmed_4" --max_sdp_iters=50000

#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=5 --output_dir="../experiments/exp_ecc_pubmed_5" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=6 --output_dir="../experiments/exp_ecc_pubmed_6" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=7 --output_dir="../experiments/exp_ecc_pubmed_7" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=8 --output_dir="../experiments/exp_ecc_pubmed_8" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=9 --output_dir="../experiments/exp_ecc_pubmed_9" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=10 --output_dir="../experiments/exp_ecc_pubmed_10" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=11 --output_dir="../experiments/exp_ecc_pubmed_11" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=12 --output_dir="../experiments/exp_ecc_pubmed_12" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=13 --output_dir="../experiments/exp_ecc_pubmed_13" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=14 --output_dir="../experiments/exp_ecc_pubmed_14" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=15 --output_dir="../experiments/exp_ecc_pubmed_15" --max_sdp_iters=50000
#python ecc.py --data_path ../data/pubmed_processed.pkl --seed=16 --output_dir="../experiments/exp_ecc_pubmed_16" --max_sdp_iters=50000
python ecc.py --data_path ../data/pubmed_processed.pkl --seed=17 --output_dir="../experiments/exp_ecc_pubmed_17" --max_sdp_iters=50000
python ecc.py --data_path ../data/pubmed_processed.pkl --seed=18 --output_dir="../experiments/exp_ecc_pubmed_18" --max_sdp_iters=50000
python ecc.py --data_path ../data/pubmed_processed.pkl --seed=19 --output_dir="../experiments/exp_ecc_pubmed_19" --max_sdp_iters=50000
python ecc.py --data_path ../data/pubmed_processed.pkl --seed=20 --output_dir="../experiments/exp_ecc_pubmed_20" --max_sdp_iters=50000
python ecc.py --data_path ../data/pubmed_processed.pkl --seed=21 --output_dir="../experiments/exp_ecc_pubmed_21" --max_sdp_iters=50000
python ecc.py --data_path ../data/pubmed_processed.pkl --seed=22 --output_dir="../experiments/exp_ecc_pubmed_22" --max_sdp_iters=50000
python ecc.py --data_path ../data/pubmed_processed.pkl --seed=23 --output_dir="../experiments/exp_ecc_pubmed_23" --max_sdp_iters=50000
python ecc.py --data_path ../data/pubmed_processed.pkl --seed=24 --output_dir="../experiments/exp_ecc_pubmed_24" --max_sdp_iters=50000

#python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=0 --output_dir="../experiments/exp_mlcl_pubmed_0" --max_sdp_iters=50000
#python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=1 --output_dir="../experiments/exp_mlcl_pubmed_1" --max_sdp_iters=50000
#python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=2 --output_dir="../experiments/exp_mlcl_pubmed_2" --max_sdp_iters=50000
#python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=3 --output_dir="../experiments/exp_mlcl_pubmed_3" --max_sdp_iters=50000
#python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=4 --output_dir="../experiments/exp_mlcl_pubmed_4" --max_sdp_iters=50000

python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=5 --output_dir="../experiments/exp_mlcl_pubmed_5" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=6 --output_dir="../experiments/exp_mlcl_pubmed_6" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=7 --output_dir="../experiments/exp_mlcl_pubmed_7" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=8 --output_dir="../experiments/exp_mlcl_pubmed_8" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=9 --output_dir="../experiments/exp_mlcl_pubmed_9" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=10 --output_dir="../experiments/exp_mlcl_pubmed_10" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=11 --output_dir="../experiments/exp_mlcl_pubmed_11" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=12 --output_dir="../experiments/exp_mlcl_pubmed_12" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=13 --output_dir="../experiments/exp_mlcl_pubmed_13" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=14 --output_dir="../experiments/exp_mlcl_pubmed_14" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=15 --output_dir="../experiments/exp_mlcl_pubmed_15" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=16 --output_dir="../experiments/exp_mlcl_pubmed_16" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=17 --output_dir="../experiments/exp_mlcl_pubmed_17" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=18 --output_dir="../experiments/exp_mlcl_pubmed_18" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=19 --output_dir="../experiments/exp_mlcl_pubmed_19" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=20 --output_dir="../experiments/exp_mlcl_pubmed_20" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=21 --output_dir="../experiments/exp_mlcl_pubmed_21" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=22 --output_dir="../experiments/exp_mlcl_pubmed_22" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=23 --output_dir="../experiments/exp_mlcl_pubmed_23" --max_sdp_iters=50000
python mlcl.py --data_path ../data/pubmed_processed.pkl --seed=24 --output_dir="../experiments/exp_mlcl_pubmed_24" --max_sdp_iters=50000
